chore: upgrade the Deny List function to SDK v3
cdklabs/construct-hub pull request #1441
Opened 2024-09-09 16:09 UTC by otaviomacedo

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-09-10 14:19 UTC, mrgrain commented on src/__tests__/streams.ts
> +export function stringToStream(s: string): any {
Can we type this correctly?
```suggestion
export function stringToStream(s: string): any {
```

2024-09-10 14:22 UTC, mrgrain commented on src/backend/shared/aws.lambda-shared.ts
> +    }
This might still work, but the docs [1] indicate we should use `cause.name` and probably also `instanceof NotFound`
```suggestion
    if (cause instanceof NotFound || cause.name === 'NotFound') {
      return false;
    }
```


[1] https://aws.amazon.com/blogs/developer/service-error-handling-modular-aws-sdk-js/

2024-09-10 14:25 UTC, mrgrain commented on src/backend/shared/aws.lambda-shared.ts
> +);
Are the old-style helper functions `ecs()` and `s3()` further down still in use elsewhere, or can they be removed now?

2024-09-10 14:28 UTC, mrgrain commented on src/__tests__/backend/catalog-builder/catalog-builder.lambda.test.ts
>  import { AWSError } from 'aws-sdk';
Should this be removed?

2024-09-10 14:29 UTC, mrgrain commented on src/__tests__/backend/catalog-builder/catalog-builder.lambda.test.ts
>  import * as AWSMock from 'aws-sdk-mock';
Same here. Can this be removed now?

2024-09-10 14:53 UTC, otaviomacedo commented on src/backend/shared/aws.lambda-shared.ts
> +);
They are still being used by the Task Monitor. I was going to add it to this PR, but I realized that there are no tests for it. So I want to upgrade and add tests in a separate PR.

2024-09-10 15:02 UTC, mrgrain commented on src/__tests__/backend/deny-list/client.test.ts
> +  (err as any).code = 'NoSuchBucket';
Error handling, similar to the other comment. The client-s3 package might even export an `NoSuchBucket` error you can use. (It does export `NotFound` which I think is only used for objects.)

2024-09-10 15:05 UTC, mrgrain commented on src/backend/catalog-builder/catalog-builder.lambda.ts
> +    if (e.code !== 'NoSuchKey') throw e;
error handling, see other comments

2024-09-10 15:06 UTC, mrgrain requested changes
Mostly left some comments about error handling for you to check. Couple of small other ones.

2024-09-11 10:15 UTC, mrgrain commented on .projenrc.ts
> +    '@smithy/util-stream',
Looks like this is in twice now.
```suggestion
```

2024-09-11 10:15 UTC, mrgrain commented on .projenrc.ts
> +    'aws-sdk-client-mock',
Also a duplicate.
```suggestion
```

2024-09-11 10:18 UTC, mrgrain approved these changes

2024-09-11 10:59 UTC, merged