chore(security): network-isolate transliterator function
cdklabs/construct-hub pull request #164
Opened 2021-07-09 11:20 UTC by RomainMuller

Run the transliterator function in isolated subnets of a dedicated VPC,
and use VPC endpoints to access S3 and CodeArtifact, so that any code
executed by the transliterator function may only access those resources.

Fixes #102 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-07-11 15:14 UTC, eladb requested changes
Missing unit tests

2021-07-11 15:14 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> -export async function handler(event: S3Event, context: Context): Promise<readonly S3Object[]> {
why? (curious)

2021-07-11 15:14 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> +    if (endpoint == null) {
style: I prefer `if (!endpoint)` so it treats empty strings as falsy

2021-07-11 15:14 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> +        console.log(`Source version was replaced by a newer one: ${object.VersionId}`);
It is quite hard to review this to know that there were no unexpected regssions (and sadly we still don't have unit tests to vouch for that). Any chance you could find a way to reduce the diff here to reflect the functional change? For example, I am not sure there's too much value in restoring HOME after this is done, so maybe the indentation around `withFakeHome()` can be avoided.

2021-07-11 15:14 UTC, eladb commented on src/codeartifact/repository.ts
> +export class Repository extends Construct implements IRepository {
docstrings

2021-07-11 15:14 UTC, eladb commented on src/codeartifact/repository.ts
> +      policy: {
I think there's a way for `AwsCustomResource` to deduce this policy automatically, no?

2021-07-11 15:14 UTC, eladb commented on src/codeartifact/repository.ts
> +    this.s3BucketArn = domainDescription.getResponseField('domain.s3BucketArn');
Why do we need the s3 bucket?

2021-07-11 15:14 UTC, eladb commented on src/codeartifact/repository.ts
> +  public get npmRepositoryEndpoint(): string {
Are you telling me there is no CFN attribute that returns the npm repository endpoint from the native CFN resource??

2021-07-11 15:14 UTC, eladb commented on src/codeartifact/repository.ts
> +        policy: {
same comment about auto-generated policy - https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html#custom-resource-execution-policy

2021-07-11 15:14 UTC, eladb commented on src/construct-hub.ts
> +        service: new ec2.InterfaceVpcEndpointAwsService('codeartifact.api'),
Feels like this should be somewhere inside the CodeArtifact L2, no?

2021-07-11 15:14 UTC, eladb commented on src/s3/vpc_endpoint_bucket.ts
> +import { GatewayVpcEndpoint } from '@aws-cdk/aws-ec2';
Use `-` instead of `_` in file names

2021-07-12 07:49 UTC, RomainMuller commented on src/backend/transliterator/transliterator.lambda.ts
> -export async function handler(event: S3Event, context: Context): Promise<readonly S3Object[]> {
This is a tiny reduction in overhead... The implementation now only does safe logging, then returning the promise from an `async` function, so there is no need for wrapping it up. That is mostly cosmetic though.

2021-07-12 07:49 UTC, RomainMuller commented on src/backend/transliterator/transliterator.lambda.ts
> +    if (endpoint == null) {
I _usually_ specifically care for "not set" and not "falsy"... But this is ONE case where I care about falsy... So good catch :)

2021-07-12 07:51 UTC, RomainMuller commented on src/backend/transliterator/transliterator.lambda.ts
> +        console.log(`Source version was replaced by a newer one: ${object.VersionId}`);
The restoration of `HOME` is specifically to avoid possibly weird side-effects from the next invocation of the Lambda function running with the `HOME` of the previous one, and weird things happening. I rather clean those up and get errors I can comprehend.

2021-07-12 07:53 UTC, RomainMuller commented on src/codeartifact/repository.ts
> +      policy: {
There probably is, but:

- I find it makes the call pattern heavier (because then I have to use variables to store the API call parameters, which I would rather not do)
- The documentation doesn't tell me _anything at all_ about _how_ it goes from API call parameters to policy... And I have strong doubts it will actually limit that to the relevant resource ARNs...

2021-07-12 07:54 UTC, RomainMuller commented on src/codeartifact/repository.ts
> +    this.s3BucketArn = domainDescription.getResponseField('domain.s3BucketArn');
When you use VPC endpoints for CodeArtifacts, you also need an S3 VPC endpoint, because the CodeArtifact repositories apparently serve the package bundles directly from an S3 bucket they control... This is used to be able to set the correct policy entries in the S3 VPC Endpoint.

2021-07-12 07:54 UTC, RomainMuller commented on src/codeartifact/repository.ts
> +  public get npmRepositoryEndpoint(): string {
Nope, there is not. And I find this about as horrifying as you do.

2021-07-12 07:55 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> +    if (endpoint == null) {
If you only want to capture "not set", then you should use `=== undefined` because `== null` will also capture an explicitly set `null` value. Just sayin'

2021-07-12 07:56 UTC, RomainMuller commented on src/construct-hub.ts
> +        service: new ec2.InterfaceVpcEndpointAwsService('codeartifact.api'),
In fact, all the other ones appear to be in the EC2 library... But CodeArtifact isn't supported there yet.

2021-07-12 07:56 UTC, RomainMuller commented on src/s3/vpc_endpoint_bucket.ts
> +import { GatewayVpcEndpoint } from '@aws-cdk/aws-ec2';
Yeah.... why'd I use underscores here? It's not my style 😳

2021-07-12 07:57 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> +        console.log(`Source version was replaced by a newer one: ${object.VersionId}`);
OK, so I would recommend to still find a way to minimize the diff to give reviewers confidence that this is not completely breaking this flow. Again, a unit test would go a long way to prove that but given this is not covered by tests, the best we can do is make sure code reviewers can verify that this change is legit.

2021-07-12 07:58 UTC, eladb commented on src/codeartifact/repository.ts
> +    this.s3BucketArn = domainDescription.getResponseField('domain.s3BucketArn');
Can this whole thing be encapsulated without exposing into a public API?

2021-07-12 07:58 UTC, eladb commented on src/codeartifact/repository.ts
> +  public get npmRepositoryEndpoint(): string {
Worth sending a note to the CodeArtifact team about this

2021-07-12 08:09 UTC, RomainMuller commented on src/backend/transliterator/transliterator.lambda.ts
> +        console.log(`Source version was replaced by a newer one: ${object.VersionId}`);
The transliterator function _does_ have unit tests... And they did not require changing.

2021-07-12 08:48 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> +        console.log(`Source version was replaced by a newer one: ${object.VersionId}`);
Okay, so please add coverage in those tests to the new behavior.

2021-07-12 08:51 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> -export async function handler(event: S3Event, context: Context): Promise<readonly S3Object[]> {
For my education, is there a difference ("tiny reduction of overhead") between?

```js
async function foo(): Promise {
  return somethingThatReturnsPromise();
}
```

and:

```js
function foo(): Promise {
  return somethingThatReturnsPromise();
}
```

2021-07-12 08:52 UTC, eladb commented on src/codeartifact/repository.ts
> +  grantReadFromRepository(grantee: IGrantable): Grant;
Why not just `grantRead()` (the "from repository" doesn't really add much, no?)

2021-07-12 08:54 UTC, eladb commented on src/codeartifact/repository.ts
> +  readonly npmRepositoryEndpoint: string;
We have an awslint rule that values that resolve during deployment (attributes) are always prefixed by the resource name. So in this case I would call this: `repositoryNpmEndpoint`.

(same for the other attributes like `domainArn` => `repositoryDomainArn`)

2021-07-12 10:49 UTC, RomainMuller commented on src/codeartifact/repository.ts
> +  grantReadFromRepository(grantee: IGrantable): Grant;
Not sure... Basically, there are "read-only" operations on the repository configuration (control-plane), and there is reading from the repository itself (data-plane, e.g: via `npm`). Both of those can exist, although for pragmatic reasons I currently only care about the later.

2021-07-12 11:24 UTC, RomainMuller commented on src/backend/transliterator/transliterator.lambda.ts
> -export async function handler(event: S3Event, context: Context): Promise<readonly S3Object[]> {
Yeah there is a theoretical reduction in overhead (it is possible they both are optimised to the same thing by V8).

2021-07-12 12:28 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> -export async function handler(event: S3Event, context: Context): Promise<readonly S3Object[]> {
TIL

I was certain it's the exact same thing.

2021-07-12 12:33 UTC, eladb requested changes

2021-07-12 12:33 UTC, eladb commented on src/backend/transliterator/index.ts
> +  readonly codeArtifact: Repository;
What would it take to make this optional? So private instances can decide if they want to use this proxy or not.

2021-07-12 12:33 UTC, eladb commented on src/backend/transliterator/index.ts
> +  readonly vpcEndpoints: TransliteratorVpcEndpoints;
Docstrings

2021-07-12 12:33 UTC, eladb commented on src/backend/transliterator/transliterator.lambda.ts
> +        console.log(`Source version was replaced by a newer one: ${object.VersionId}`);
👆

2021-07-12 12:33 UTC, eladb commented on src/codeartifact/repository.ts
> +  readonly registryname?: string;
```suggestion
  readonly registryName?: string;
```

2021-07-12 12:33 UTC, eladb commented on src/codeartifact/repository.ts
> +  grantReadFromRepository(grantee: IGrantable): Grant;
Ok.

2021-07-12 14:31 UTC, RomainMuller commented on src/backend/transliterator/index.ts
> +  readonly codeArtifact: Repository;
It would be _super_ easy, as I've made the worker able to operate with AND without the code artefact repository settings. So technically it's simply propagating optionals around everywhere, that is it.

2021-07-12 14:35 UTC, eladb commented on src/backend/transliterator/index.ts
> +  readonly codeArtifact: Repository;
If it's easy, I rather we do it now so we keep this option alive going forward. Later it might be harder.

2021-07-13 13:27 UTC, eladb approved these changes

2021-07-13 13:28 UTC, merged