chore: solve snapshots
cdklabs/construct-hub pull request #171
Opened 2021-07-13 11:55 UTC by iliapolo

Found the culprit: https://github.com/aws/aws-cdk/issues/15523

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-07-13 12:32 UTC, eladb requested changes

2021-07-13 12:32 UTC, eladb commented on src/webapp/index.ts
> +    const functionName = `${Names.uniqueId(this)}${functionId}`;
I would just use `Node.of(this).addr` which has a stable length

2021-07-15 08:08 UTC, iliapolo commented on src/webapp/index.ts
> +          functionName: this.node.addr, // see https://github.com/aws/aws-cdk/issues/15523
`this` here is the `WebApp` construct, not the function - wouldn't it make sense to append the function construct id to it to mimic the address of the actual function?

2021-07-15 08:10 UTC, eladb commented on src/webapp/index.ts
> +          functionName: this.node.addr, // see https://github.com/aws/aws-cdk/issues/15523
Yes, you are right.

2021-07-15 08:13 UTC, eladb commented on src/webapp/index.ts
> +          functionName: this.node.addr, // see https://github.com/aws/aws-cdk/issues/15523
done

2021-07-15 08:15 UTC, eladb approved these changes

2021-07-15 08:15 UTC, merged