feat: deny list
cdklabs/construct-hub pull request #174
Opened 2021-07-14 09:16 UTC by eladb

Allow users to specify deny list rules for the construct hub. Rules can match a package name and optionally a specific version. If a package is matched against a rule, the package is ignored and a log entry is emitted with the reason information.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-07-27 09:00 UTC, RomainMuller requested changes

2021-07-27 09:18 UTC, eladb commented on .projenrc.js
> +  ts.line('...props,');
Good call. Shuffled.

2021-07-27 09:18 UTC, eladb commented on .projenrc.js
> +    ts.open('new AfterCreate(this, \'Trigger\', {');
Why not

2021-07-27 09:23 UTC, eladb commented on README.md
> +  by `deploy` as well)
Done.

2021-07-27 09:24 UTC, eladb commented on src/__tests__/backend/deny-list/client.test.ts
> +  process.env[ENV_DENY_LIST_OBJECT_KEY] = 'deny-list.json';
No... `ENV_DENY_LIST_BUCKET_NAME` is a constant that has the environment variable name in it so phases are strongly coupled instead of weakly coupled.

2021-07-27 09:24 UTC, eladb commented on src/__tests__/backend/deny-list/client.test.ts
> +});
Done.

2021-07-27 09:25 UTC, eladb commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +const mockPackageDataDir = join(__dirname, '..', '..', '..', '..', '..', 'src', '__tests__', 'backend', 'deny-list', 'integ', 'package-data');
Yes, I don't want them in the tarball... Let me see...

2021-07-27 09:27 UTC, eladb commented on .projenrc.js
> +    ts.open('new AfterCreate(this, \'Trigger\', {');
Well... `ts.line()` adds a line with indentation which fails the linter, so I am passing on this one for now.

2021-07-27 09:32 UTC, eladb commented on .projenrc.js
> +    ts.open('new AfterCreate(this, \'Trigger\', {');
Fix is here: https://github.com/projen/projen/pull/952

2021-07-27 09:33 UTC, eladb commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +  after: [denylist],
Changed to `invokeAfter`

2021-07-27 10:03 UTC, eladb commented on src/webapp/cache-invalidator/handler.lambda.ts
> +      CallerReference: context.awsRequestId,
It's not really an idempotency token since a call will _fail_ if caller reference is reused (idempotency means that the call will succeed with a no-op). This happened because an invalidation that was triggered by a CREATE and then DELETE of the same object used the same reference. I could add the type of S3 event to the eTag as the caller reference was generated but after reading the [CloudFront API Documentation](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateInvalidation.html#cloudfront-CreateInvalidation-request-CallerReference), which suggests to use a _timestamp_ for the CallerReference, I thought using the request ID is 
actually the cleanest solution.

See also [this SO article](https://stackoverflow.com/questions/6514983/what-is-callerreference-for-when-posting-an-invalidation-request-to-amazon-cloud)

2021-07-27 10:05 UTC, eladb commented on src/backend/discovery/discovery.lambda.ts
> +            console.log(`[${change.seq}] Package denied: ${JSON.stringify(denied)}`);
done

2021-07-27 10:05 UTC, eladb commented on src/backend/discovery/discovery.lambda.ts
> +  denyList: DenyListClient): readonly UpdatedVersion[] {
really?! ok...

2021-07-27 10:10 UTC, eladb commented on src/backend/discovery/discovery.lambda.ts
> +  await denyList.init(); // downloads denylist from s3
Nice! I like the async factory option

2021-07-27 10:11 UTC, eladb commented on src/backend/discovery/constants.lambda-shared.ts
> +  DENIED_COUNT = 'DeniedCount',
Done

2021-07-27 10:12 UTC, eladb commented on src/backend/deny-list/prune.ts
> +    props.catalogBuilderFunction.grantInvoke(deleteHandler);
Yes, interesting observation but still... If you are familiar with CDK grants, then the semantic reads "catalog builder, please grant the delete handler permissions to invoke you. thank yew"

2021-07-27 10:15 UTC, eladb commented on src/backend/deny-list/prune.ts
> +    props.packageDataBucket.grantWrite(deleteHandler);
fixed. `grantDelete()`

2021-07-27 10:15 UTC, eladb commented on src/backend/deny-list/prune.ts
> +      visibilityTimeout: Duration.minutes(2), // must be > processor timeout
fixed (PruneQueueHandler)

2021-07-27 10:23 UTC, eladb commented on src/backend/deny-list/prune-queue-handler.lambda.ts
> +    const catalogRebuildResponse = await lambda.invoke(catalogRebuildRequest).promise();
Good catch. Well... just catching those errors is not going to have the right effect because we _need_ to rebuild the catalog.

I am wondering what's the best way to handle. What we want is that if the catalog builder is currently running, it should be run again once its complete.

I am wondering if we can use an SQS FIFO queue and send a message with the same de-duplication key every time. This means that in order to trigger a rebuild, users will send a message to the queue (with this de-dup key). If the builder is already running, it will get reinvoked again immediately after and if not, it will be triggered immediately.

What do you think about this design?

2021-07-27 10:32 UTC, RomainMuller commented on src/webapp/cache-invalidator/handler.lambda.ts
> +      CallerReference: context.awsRequestId,
My understanding of the docs is that it will fail ONLY if the rest of the request is different, and will idempotently succeed otherwise.

2021-07-27 10:34 UTC, eladb commented on src/backend/deny-list/prune-handler.lambda.ts
> +      }
okay, moving to individual messages. thanks

2021-07-27 10:34 UTC, RomainMuller commented on src/__tests__/backend/deny-list/client.test.ts
> +  process.env[ENV_DENY_LIST_OBJECT_KEY] = 'deny-list.json';
Oh bin yes! I misread that -_-

2021-07-27 10:36 UTC, eladb commented on src/backend/deny-list/prune-handler.lambda.ts
> +      }
done

2021-07-27 10:36 UTC, eladb commented on src/backend/deny-list/prune-handler.lambda.ts
> +export async function handler() {
added thanks for the tip

2021-07-27 10:37 UTC, eladb commented on src/backend/deny-list/prune-handler.lambda.ts
> +    metrics.putMetric(MetricName.DENY_LIST_RULE_COUNT, ruleCount, Unit.Count);
removed.

2021-07-27 10:38 UTC, RomainMuller commented on src/backend/deny-list/prune-queue-handler.lambda.ts
> +    const catalogRebuildResponse = await lambda.invoke(catalogRebuildRequest).promise();
Not sure... does the content-based deduplication "ignore" messages that are not visible? Otherwise, the new message sent to the queue will be de-duplicated against the "in flight" message that the catalog builder currently triggered off of...? I never looked into that, so I don't know... If "in flight" is not considered for deduplication, then this sounds like a pragmatic solution for sure.

I'm also afraid (but to a much lesser extent) the SQS trigger will try to fire ASAP and hit throttles until no execution is in progress anymore... Which is not ideal (although the throttle metric of this particular function is probably not that interesting to look at).

2021-07-27 10:41 UTC, eladb commented on src/backend/deny-list/prune-handler.lambda.ts
> +const sqs = new AWS.SQS();
Done.

2021-07-28 07:27 UTC, eladb commented on .npmignore
> +src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/tree.json
dah!

2021-07-28 07:28 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +    }
Done. added validations and some unit tests for them

2021-07-28 07:31 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +    const tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), 'deny-list-'));
I don't understand the problem, really. Temporary directories are conventionally cleaned up when the system reboots [reference](https://serverfault.com/questions/377348/when-does-tmp-get-cleared/377349). That's what `/tmp` is designed for. There's value in keeping those directories alive for diagnostics.

2021-07-28 07:33 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +   */
Updated.

2021-07-28 07:39 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +   * Set to `Duration.zero` to disable
It also doesn't work (which is surprising! A duration of zero is a totally legitimate value, but that's for a different discussion)

https://github.com/aws/aws-cdk/issues/15792

2021-07-28 07:44 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +    if (prunePeriod) {
Fixed. Checks for 0.

2021-07-28 07:45 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +        filters: [{ prefix: this.objectKey }],
TIL thanks

2021-07-28 07:46 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +    this.prune = prune;
Done

2021-07-28 07:47 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +    this.objectKey = 'deny-list.json';
Done.

2021-07-28 07:48 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +    });
Added `enforceSSL`

2021-07-28 07:50 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +import { Construct } from 'constructs';
Fixed - using Construct from core both as a base class and for scope.

2021-07-28 07:51 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +  readonly packageDataBucket: s3.Bucket;
Changed

2021-07-28 07:51 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +  readonly rules?: DenyListRule[];
made required

2021-07-28 07:53 UTC, eladb commented on src/backend/deny-list/deny-list.ts
> +   * @default true
done

2021-07-28 07:54 UTC, eladb commented on src/backend/deny-list/client.lambda-shared.ts
> +    this._map = {}; // reset
I've changed this function to private as it is now only called from `newClient()` so now it will just fail if called twice.

2021-07-28 07:55 UTC, eladb commented on src/backend/deny-list/client.lambda-shared.ts
> +      const body = response.Body;
ok...

2021-07-28 07:55 UTC, eladb commented on src/backend/deny-list/client.lambda-shared.ts
> +      const data = JSON.parse(body.toString()) as DenyListMap;
done.

2021-07-28 07:56 UTC, eladb commented on src/backend/deny-list/client.lambda-shared.ts
> +    }
I didn't want a failure to load the deny list to block our entire ingress, but I guess if there supposed to be some denied package and it is impossible to parse the list, we better off not ingesting anything... I'll change to an exception.

2021-07-28 07:57 UTC, eladb commented on src/backend/deny-list/client.lambda-shared.ts
> +    return entry;
done.

2021-07-28 08:54 UTC, eladb commented on src/backend/deny-list/client.lambda-shared.ts
> +  }
I'll leave like this.

2021-07-28 08:55 UTC, eladb commented on src/backend-dashboard.ts
> +                `[button:Deny List File](${s3ObjectUrl(props.denyList.bucket, props.denyList.objectKey)})`,
Done

2021-07-28 09:10 UTC, eladb commented on src/__tests__/backend/deny-list/integ/trigger.prune-test.lambda.ts
> +  while ((Date.now() - startTime) / 1000 < timeoutSec) {
Since this is just a test, I'll leave it like this if you are okay with it. I rather minimize changes at this point

2021-07-28 09:11 UTC, eladb commented on src/__tests__/backend/deny-list/integ/trigger.prune-test.lambda.ts
> +    if (JSON.stringify(keys.sort()) === JSON.stringify(expected.sort())) {
Done

2021-07-28 09:13 UTC, eladb commented on src/__tests__/backend/deny-list/integ/trigger.prune-test.lambda.ts
> +  throw new Error(`assertion failed. the following objects were not deleted after ${timeoutSec}s. Actual: ${JSON.stringify(keys)}. Expected: ${JSON.stringify(expected)}`);
You got it

2021-07-28 09:15 UTC, eladb commented on src/__tests__/backend/deny-list/integ/trigger.prune-test.lambda.ts
> +    }
Chose this:

```ts
    for (const { Key: key } of listResponse.Contents ?? []) {
      if (!key) { continue; }
      objectKeys.push(key);
    }
```

2021-07-28 09:16 UTC, eladb commented on src/backend/deny-list/client.lambda-shared.ts
> +  constructor(options: DenyListClientOptions = {}) {
Made it private actually now that we have a static async factory

2021-07-28 09:27 UTC, eladb commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +const mockPackageDataDir = join(__dirname, '..', '..', '..', '..', '..', 'src', '__tests__', 'backend', 'deny-list', 'integ', 'package-data');
Raised an issue in projen: https://github.com/projen/projen/issues/955

2021-07-28 09:42 UTC, eladb commented on src/webapp/cache-invalidator/handler.lambda.ts
> +      CallerReference: context.awsRequestId,
We decided that request ID is likely a reasonable solution

2021-07-28 09:45 UTC, eladb commented on API.md
> +#### Initializer <a name="[object Object].Initializer"></a>
Opened an issue with jsii-docgen

2021-07-28 10:08 UTC, RomainMuller approved these changes
Approved as discussed - outstanding minor comments to be handled in a subsequent PR.

2021-07-28 10:08 UTC, eladb commented on src/backend/deny-list/prune-queue-handler.lambda.ts
> +    const catalogRebuildResponse = await lambda.invoke(catalogRebuildRequest).promise();
@RomainMuller and me did some investigation and verified that since the invocation is EVENT type, the request won't fail when the function is throttled and actually will go through when the function finishes execution, which is a reasonable behavior.

In a subsequent pull request, I will change the logic so that the catalog builder will take deny list into account and the rebuild will get triggered by the prune handler itself and not the delete handler, so it will happen only once for each deny list change.

2021-07-28 10:27 UTC, eladb commented on .projenrc.js
> +    ts.open('new AfterCreate(this, \'Trigger\', {');
Fixed

2021-07-28 10:34 UTC, merged