feat: allow specific custom links
cdklabs/construct-hub pull request #321
Opened 2021-09-08 23:58 UTC by MrArnoldPalmer

Allows contruct-hub admins to specify a list of allowed links that
package authors can include in their package.json to be shown on their
package's details page. For Example:

A package author can add the following to their package.json
```json
"constructHub": {
  "links": {
    "SLA": "https://link.to.my.support.info",
    "Author": "mailto:me@you.com"
  }
}
```

Then, the administrator of construct hub can add these to an allow list
like so:
```ts
new ConstructHub(this, "ConstructHub", {
  ...myProps,
  packageLinks: [{
    name: 'Service Level Agreement',
    value: 'SLA',
  }, {
    name: 'Contact',
    value: 'Author',
    displayText: 'Email Me!',
    domains: ['me.com'],
  }]
});
```

With these links allowed, the ingestion lambda will search for these
values and place them in a package's metadata.json file. Additionally,
the configuration is put into a `config.json` file alongside the webapp
assets to be loaded by the frontend in order to determine what links to
render.

fix: #286

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-09-09 01:13 UTC, Chriscbr requested changes
This looks awesome!

I'm curious about this design - why do we need to set custom backend behavior for the `packageLinks` field? If we automatically included everything a user puts in their `constructHub` field within package.json into the corresponding metadata.json, and did the processing (removing unallowed domains) on the client side, what would the downsides/risks be?  

Also could you update the docs with a blurb about this feature? 🙏

2021-09-09 01:13 UTC, Chriscbr commented on src/webapp/config.ts
> +    };
nit: I think this would be a little easier to read if written in a more imperative style - but it might just be personal taste.
```suggestion
    const packageLinks = this.props.packageLinks ?? [];
    const withoutDomains = packageLinks.map(({ domains, ...rest }) => rest);
    return { packageLinks: withoutDomains };
```

2021-09-09 01:13 UTC, Chriscbr commented on src/backend/ingestion/ingestion.lambda.ts
> +        }
Can we add a unit test that captures this behavior somehow (maybe by extracting this section to a function)? An integ test might be nice too, but it might not be worth the effort.

2021-09-09 01:17 UTC, MrArnoldPalmer commented on src/webapp/config.ts
> +    this.dir = mkdtempSync(join(tmpdir(), 'chwebapp'));
tmpdir returns the OS's temp directory, if you mkdtemp without that as your initial path it just creates the directory in your CWD.

2021-09-09 01:17 UTC, MrArnoldPalmer commented on src/webapp/index.ts
> +export interface PackageLinkConfig {
I'm fine with these, definitely a bit more explanatory.

2021-09-09 01:18 UTC, MrArnoldPalmer commented on src/webapp/index.ts
> +      prune: false,
because the config is being uploading the same bucket as the webapp, so one deploy would overwrite the other without prune: false.

2021-09-09 01:18 UTC, MrArnoldPalmer commented on src/construct-hub.ts
> +  ) {
lol we should, I think this was Prettier running in my editor.

2021-09-09 01:18 UTC, MrArnoldPalmer commented on src/backend/ingestion/ingestion.lambda.ts
> +        }
working on this 👍🏻

2021-09-09 01:22 UTC, MrArnoldPalmer commented
> why do we need to set custom backend behavior for the packageLinks field? If we automatically included everything a user puts in their constructHub field within package.json into the corresponding metadata.json, and did the processing (removing unallowed domains) on the client side, what would the downsides/risks be?  

My instinct is that input sanitation can/should always occur on the backend and any invalid data should already be removed or corrected before being passed over the write to the client. I don't see any particular vulnerabilities in this scenario though so I could be onboard. I'd like to get opinions from @RomainMuller and @iliapolo as well though.

2021-09-09 18:23 UTC, Chriscbr commented on src/webapp/config.ts
> +    this.dir = mkdtempSync(join(tmpdir(), 'chwebapp'));
Ah I see. Yeah on second thought I've seen this pattern used in projen as well. All good

2021-09-14 07:38 UTC, RomainMuller approved these changes
This might warrant also having a page on the web app that explains what links are available for use on a particular instance.

Also I wonder if there would be an interest in specifying validation rules (i.e: a regex or something) for those values... but let's not right now.

2021-09-14 07:38 UTC, RomainMuller commented on README.md
> +});
Recommend updating the PR description to match the final API.

2021-09-14 19:33 UTC, Chriscbr approved these changes

2021-09-14 19:34 UTC, merged