feat: attempt to detect packages' construct framework
cdklabs/construct-hub pull request #330
Opened 2021-09-15 15:34 UTC by RomainMuller

This includes three major updates:

1. The NpmJS discovery function inspects the dependencies of a package,
   and will include it in scope if it has a dependency on an AWS CDK,
   cdktf or cdk8s framework package (the first-party ones), even if it
   does not feature the relevant tag.

2. The ingestion function looks at the `dependencyClosure` in the jsii
   Assembly to determine which constructs framework is being used, and
   if possible, which major version thereof. This is then added to the
   metadata object.

3. The catalog builder now removes the `licenseText` property from the
   metadata included in there, so the file will be much smaller, and
   stop including redundant text.

Fixes #326

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-09-24 01:30 UTC, MrArnoldPalmer approved these changes

2021-09-24 01:30 UTC, MrArnoldPalmer commented on src/backend/ingestion/ingestion.lambda.ts
> +  readonly name: 'aws-cdk' | 'cdk8s' | 'cdktf';
Nit: separating this into a named type seems easier when referencing it later.

2021-09-24 02:04 UTC, Chriscbr requested changes

2021-09-24 02:04 UTC, Chriscbr commented on src/backend/catalog-builder/catalog-builder.lambda.ts
> +  }
It was a little odd to me when I saw half of catalog.json was just license text - thanks for fixing this!

2021-09-24 02:04 UTC, Chriscbr commented on src/backend/ingestion/ingestion.lambda.ts
> +function detectConstructFramework(assembly: Assembly): ConstructFramework | undefined {
Can we add unit tests for this? (Or for the `isConstructLibrary` / `isConstructFrameworkPackage` functions - whichever you think makes more sense)

2021-09-24 16:40 UTC, Chriscbr approved these changes
Approving with do-not-merge since the only suggested changes are small

2021-09-27 07:02 UTC, RomainMuller commented on src/backend/ingestion/ingestion.lambda.ts
> +function detectConstructFramework(assembly: Assembly): ConstructFramework | undefined {
Those are implementation details... There is coverage through the ingestion tests already.

2021-09-27 12:11 UTC, merged