chore: pre-bundle lambda functions
cdklabs/construct-hub pull request #37
Opened 2021-05-05 17:08 UTC by eladb

The internal Amazon build system makes it extremely hard to use `esbuild` to bundle during app synthesis. So we are taking this opportunity to experiment with the idea of pre-bundling lambda functions during library build, alongside synthesis of a construct class that can be used seamlessly in the construct hub code.

The developer experience is pretty neat:

1. Create a file somewhere under the `src` tree with the `.lambda.ts` extension.
2. This file should export a single async function called `handler`.
3. Run `projen`.
4. This will do the following:
   1. Add a compile task that uses `esbuild` to create a bundle from them under `lib/xxx.bundle/index.js`
   2. Generate TypeScript code under `xxx.ts` with a construct that extends `lambda.Function` which points to the bundled asset.

Now, in your CDK code, just import the generated construct and use it.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-05 17:44 UTC, polothy commented
I'm not super familiar with `esbuild`, but if my lambda handler used some random NPM package or maybe a specific version of the JS AWS SDK, would `esbuild` bundle those dependencies into the bundled lambda output (EG: in `lib/xxx.bundle/index.js`)?

2021-05-05 17:49 UTC, eladb commented
> I'm not super familiar with `esbuild`, but if my lambda handler used some random NPM package or maybe a specific version of the JS AWS SDK, would `esbuild` bundle those dependencies into the bundled lambda output (EG: in `lib/xxx.bundle/index.js`)?

Yessir

2021-05-05 19:38 UTC, hoegertn commented on .projenrc.js
> +  ts.open(`export interface ${propsName} extends Omit<lambda.FunctionProps, 'code' | 'handler' | 'runtime'> {`);
I would love this but the Omit makes JSII sad. Any ideas?

2021-05-05 19:50 UTC, eladb commented on .projenrc.js
> +  ts.open(`export interface ${propsName} extends Omit<lambda.FunctionProps, 'code' | 'handler' | 'runtime'> {`);
Changed to use `FunctionOptions` instead

2021-05-06 08:24 UTC, iliapolo requested changes

2021-05-06 08:24 UTC, iliapolo commented on .projenrc.js
> +  const entry = `src/${entrypoint}`;
```suggestion
  const entry = `${project.srcdir}/${entrypoint}`;
```

2021-05-06 08:24 UTC, iliapolo commented on .projenrc.js
> +  const infra = `src/${dir}.ts`;
```suggestion
  const infra = `${project.srcdir}/${dir}.ts`;
```

2021-05-06 08:24 UTC, iliapolo commented on .projenrc.js
> +  const outdir = `lib/${dir}.bundle`;
```suggestion
  const outdir = `${project.libdir}/${dir}.bundle`;
```

2021-05-06 08:24 UTC, iliapolo commented on .projenrc.js
> +  console.error(`${base}: bundle task "${bundle.name}"`);
Debug leftovers?

2021-05-06 08:27 UTC, eladb commented on .projenrc.js
> +  console.error(`${base}: bundle task "${bundle.name}"`);
No, this is intentional

2021-05-06 08:30 UTC, iliapolo approved these changes

2021-05-06 08:30 UTC, merged

2021-05-06 16:47 UTC, pgollucci commented
I'm going to take this for a swing in p6-namer.  Hopefully we can move it to ts, 2.0, this.  The idea and convention is imho better than the current lambdanodejs, I feel like the naming conventions are more consistent.

How does this flow to the other langs?