feat: option to skip docgen after re-ingesting packages
cdklabs/construct-hub pull request #505
Opened 2021-11-06 01:22 UTC by Chriscbr

This adds a "skipDocgen" option to make it easier to defer regenerating all docs when all you need to do is update package metadata objects after making a change to `packageTags` or `packageLinks`, for example.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-06 01:26 UTC, Chriscbr commented on src/backend/ingestion/index.ts
> +      },
I didn't want the state machine to fail if the user _doesn't_ specify a value for `skipDocgen`, so I store the user's initial input to the state machine in `$.params`.

2021-11-08 08:29 UTC, RomainMuller requested changes

2021-11-08 08:29 UTC, RomainMuller commented on src/backend/ingestion/index.ts
> + * docs re-generated. This can be skipped by passing { "skipDocgen": true } in
The `skipDocgen` value is not passed back into "continue as new" executions (see L376-387 in this file).

2021-11-08 08:29 UTC, RomainMuller commented on src/backend/ingestion/index.ts
> +    }).next(new Choice(this, 'Has a ContinuationToken?')
This doesn't seem necessary to me... The `Map` state runs a completely encapsulated state machine, and you can "locally" do this using it's `parameters`.

2021-12-01 21:13 UTC, Chriscbr commented
Closing for now since it doesn't seem too high priority (though I'm open to fixing it up if anyone thinks it would be useful)

2021-12-01 21:13 UTC, closed without merging