feat: support limited internet access mode
cdklabs/construct-hub pull request #512
Opened 2021-11-08 19:06 UTC by RomainMuller

Introduced a new isolation mode that allows ConstructHub to access
internet, but only on certain CIDR ranges (those of CloudFlare - which
fronts `registry.npmjs.com`, and some of the ranges from GitHub).

This allows removing the hard dependency on CodeArtifact while
maintaining a balanced security posture around downloading & installing
third-party artifacts for documentation-generation purposes.

The CIDR lists are automatically kept up-to-date by GitHub workflows,
triggering on a daily basis, which will cut a PR to update the CIDR
allow-list files whenever they change.

The network restrictions are implemented by way of a series of
SecurityGroups (we need multiple groups, as these are limited to 60
rules each, and there are more than 60 CIDR blocks today), which are
registered on the compute tasks that perform work that is deemed "risky".

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-11 15:11 UTC, eladb requested changes

2021-11-11 15:11 UTC, eladb commented on src/construct-hub.ts
> +        .map((cidr) => ({ cidr }));
Extract to a separate function

2021-11-15 10:47 UTC, RomainMuller commented on src/construct-hub.ts
> +   * @default Isolation.NO_INTERNET_ACCESS
> Since we now understand the CodeArtifact cannot support the Hub

That statement is incorrect.

> From a risk perspective, I expected this PR to be mostly deletions of code, so we can simplify the backend. This change feels like it adds complexity instead.

This change was designed in accordance with recommendations from security. Complete isolation from internet (which implies CodeArtifact) remains security's preferred solution, and they explicitly asked us to get back to this once the current issues are resolved.

2021-11-15 10:48 UTC, RomainMuller commented on src/construct-hub.ts
> +    if (props.isolateSensitiveTasks != null && props.sensitiveTaskIsolation != null) {
This is a relatively steep change in security posture and we _specifically_ need to be able to enable `LIMITED` mode strictly on Gamma for QA testing, first. Your suggestion would cause Gamma & Prod to get the new behavior faster than we would want.

2021-11-15 11:52 UTC, eladb approved these changes

2021-11-15 11:57 UTC, merged