fix: normal-severity action not registered
cdklabs/construct-hub pull request #555
Opened 2021-11-16 12:25 UTC by RomainMuller

When submitted as ARNs instead of IAlarmAction, normal
severity alarm actions were not bound to the alarms as
they should have.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-16 12:29 UTC, eladb requested changes

2021-11-16 12:29 UTC, eladb commented on src/monitoring/index.ts
> +    if (this.alarmActions?.normalSeverityAction) {
Now it seems like this is adding the normal severity action twice.

Also - missing test?

2021-11-16 13:51 UTC, eladb requested changes

2021-11-16 13:51 UTC, eladb commented on src/monitoring/index.ts
> +    const highSeverityAction = this.alarmActions?.normalSeverityAction;
```suggestion
    const highSeverityAction = this.alarmActions?.highSeverityAction;
```

2021-11-16 13:51 UTC, eladb commented on src/__tests__/monitoring.test.ts
> +test('low-severity alarm actions are registered', () => {
What about high severity?

Isn't this called "normal severity"?

2021-11-16 16:04 UTC, RomainMuller commented on src/__tests__/monitoring.test.ts
> +test('low-severity alarm actions are registered', () => {
> What about high severity?

I don't normally get in the business of adding missing test coverage on code paths unrelated to my changes... but I've added that now.

> Isn't this called "normal severity"?

Ah yes! Fixed.

2021-11-16 16:10 UTC, eladb commented on src/__tests__/monitoring.test.ts
> +test('low-severity alarm actions are registered', () => {
> I don't normally get in the business of adding missing test coverage on code paths unrelated to my changes... but I've added that now.

If possible, why not?

2021-11-16 16:11 UTC, eladb approved these changes

2021-11-18 15:27 UTC, merged

2021-11-18 15:33 UTC, RomainMuller commented on src/__tests__/monitoring.test.ts
> +test('low-severity alarm actions are registered', () => {
To keep the diff small & focused.