fix: deny-list integ test does not clean up successfully
cdklabs/construct-hub pull request #634
Opened 2021-12-01 21:15 UTC by Chriscbr

Fixes #541

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-01 21:32 UTC, eladb requested changes

2021-12-01 21:32 UTC, eladb commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +denylist.bucket.applyRemovalPolicy(RemovalPolicy.DESTROY);
Perhaps expose this option in the deny list props instead of calling private methods

2021-12-01 21:46 UTC, Chriscbr commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +denylist.bucket.applyRemovalPolicy(RemovalPolicy.DESTROY);
Good idea! Updated

2021-12-02 07:09 UTC, eladb requested changes

2021-12-02 07:09 UTC, eladb commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +  // allow integ test to self-clean-up
Now that I am thinking about this. Any reason this bucket won't have these properties in production as well? The contents are static and uploaded from an assert.

Let's just make this the behavior.

2021-12-02 20:18 UTC, Chriscbr commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +  // allow integ test to self-clean-up
Mmm ok. I guess if the contents of the deny-list are static / provided in source control by the deployment, then retaining the bucket when a stack is deleted probably doesn't provide much value?

If I understand correctly, I think it should be ok if this self-clean-up behavior also applies to the failover buckets, since it is only relevant when stacks are being deleted.

2021-12-05 12:06 UTC, eladb commented on src/__tests__/backend/deny-list/integ/deny-list.integ.ts
> +  // allow integ test to self-clean-up
The fail-over buckets of the deny list, not the ones that store "real data".

Generally speaking I don't think something like the deny list really needs a fail-over bucket because the bucket just reflects some state from the source code.

2021-12-05 12:07 UTC, eladb approved these changes

2021-12-05 12:07 UTC, merged