chore: update AWS CDK version
cdklabs/construct-hub pull request #648
Opened 2021-12-07 23:47 UTC by Chriscbr

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-07 23:48 UTC, Chriscbr commented on src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/TestDenyList.template.json
> +        "aws:asset:original-path": "/Volumes/workplace/construct-hub/node_modules/@aws-cdk/aws-s3-deployment/lib/lambda",
hmm this doesn't look right... I suppose these files shouldn't be version controlled?

2021-12-08 00:13 UTC, Chriscbr commented on src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/TestDenyList.template.json
> +        "aws:asset:original-path": "/Volumes/workplace/construct-hub/node_modules/@aws-cdk/aws-s3-deployment/lib/lambda",
I added these file to our gitignore... but now I realize that doesn't seem correct either, because everything else in the cdkout directory is also ignored -- so now our "diff" snapshots would be doing nothing.

It looks like this is the root cause: https://github.com/aws/aws-cdk/pull/17591

@eladb This should be fixed within projen.

For now I'm going to downgrade from v1.34.0 to v1.33.0.

2021-12-08 01:07 UTC, Chriscbr commented
I'm having issues upgrading to a non-latest version of the AWS CDK, getting the infamous yarn error:

```
error An unexpected error occurred: "expected hoisted manifest for \"cdk-watchful#@aws-cdk/aws-cloudwatch#@aws-cdk/core\"".
```

so... probably going to put this on hold for now.

2021-12-08 06:47 UTC, eladb commented
> I'm having issues upgrading to a non-latest version of the AWS CDK, getting the infamous yarn error:
> 
> ```
> error An unexpected error occurred: "expected hoisted manifest for \"cdk-watchful#@aws-cdk/aws-cloudwatch#@aws-cdk/core\"".
> ```
> 
> so... probably going to put this on hold for now.

This looks familiar. @RomainMuller any idea?

Also - why not use AWS CDK v2?

2021-12-09 23:57 UTC, Chriscbr commented
Updated to AWS CDK v1.134.0. Integration test snapshots now use the --no-asset-metadata flag to work around the snapshots issue.

> Also - why not use AWS CDK v2?

See #108.

2021-12-12 14:40 UTC, eladb requested changes
Would it make sense to upgrade to v2?

2021-12-20 22:48 UTC, closed without merging