feat: reprocess all packages on a daily basis
cdklabs/construct-hub pull request #677
Opened 2021-12-14 21:53 UTC by Chriscbr

Closes #669

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-14 22:23 UTC, MrArnoldPalmer requested changes

2021-12-14 22:23 UTC, MrArnoldPalmer commented on docs/operator-runbook.md
> +desirable to lower this frequency or disable the cron job altogether. This
I kinda think the default should be `never reprocess` and it should be explicitly opt-in to enable some timed reprocess interval. Using `Duration.days(0)` though somewhat familiar still feels clunky and unclear.

2021-12-14 23:25 UTC, Chriscbr commented on docs/operator-runbook.md
> +desirable to lower this frequency or disable the cron job altogether. This
Mmm, yeah that's a good point. Updated.

2021-12-15 00:28 UTC, MrArnoldPalmer approved these changes

2021-12-15 00:41 UTC, merged