Feat/support search group labels
cdklabs/construct-hub pull request #685
Opened 2021-12-28 00:02 UTC by gabewomble

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

This pull request implements another config update which allows operators to customize search filter groups via the `packageTagGroups` prop. It allows specifying a custom label, tooltip, and if the filter should be a checkbox (multi-select) or a radio (single-select). Additionally, this feature is backwards-compatible

To see usage of the new config, look at the dev-stack.ts file in the diff.

To see this feature on a custom deployment (with the front-end feature implemented as well) visit this deployment: https://d3u0cndfkrxv5v.cloudfront.net/search?q=&offset=0

<img width="242" alt="Screen Shot 2021-12-27 at 4 01 54 PM" src="https://user-images.githubusercontent.com/8749859/147514613-dbd02fc7-838b-4798-968a-6c2d2e6021d9.png">

2021-12-28 20:18 UTC, MrArnoldPalmer requested changes
Overall the API looks great. There may be some argument for increased use of classes over interfaces for `TagGroupConfig` so instead of passing a string  to `groupBy` you pass an instance of `TagGroupConfig`. This feels like it would be more `cdk`-style but idk of any benefits beyond that.

Just changing the literal union to be more JSII friendly is the only thing I'd argue to do now.

2021-12-28 20:18 UTC, MrArnoldPalmer commented on src/package-tag/index.ts
> +  readonly filterType?: 'checkbox' | 'radio';
So we probably want to avoid the union here for JSII reasons, as this is part of the public interface for the construct.

We could make this a similar 'union like class' to `TagCondition` so like `FilterType.checkbox()` | `FilterType.radio()` type thing where the type is `FilterType`.

2021-12-29 17:51 UTC, Chriscbr reviewed
Looks great. 😊 Reminder to be sure to update tag explanation/examples in README.md.

2021-12-29 17:51 UTC, Chriscbr commented on src/__tests__/devapp/dev-stack.ts
> +const makeUseCaseTag = (label: string, useCase: TagCondition) => ({
Is there a return type for this we can annotate with this with?

2021-12-30 19:38 UTC, MrArnoldPalmer approved these changes
Added `do-not-merge` to allow acting on comments at your discretion. Easily can be handled at a later time.

2021-12-30 19:38 UTC, MrArnoldPalmer commented on src/package-tag-group/index.ts
> +}
mostly nits as all of these changes could be made without affecting (what is meant to be) the public API.

Defining separate classes that extend `FilterType` would take away the need for string constructor arguments. Also usage of the `bind` pattern for returning some common/serializable config would be closer to existing convention.

```ts
export interface FilterTypeValue {
  type: 'checkbox' | 'radio'
}

class FilterTypeCheckbox extends FilterType {
  public bind(): FilterTypeValue {
    return { type: 'checkbox' };
  }
}

class FilterTypeRadio extends FilterType {
  public bind(): FilterTypeValue {
    return { type: 'radio' };
  }
}

export abstract class FilterType {
  static checkbox(): FilterTypeValue {
    return new FilterTypeCheckbox();
  }

  static radio(): FilterTypeValue {
    return new FilterTypeRadio();
  }
  
  public abstract bind(): FilterTypeValue;
}
```

2021-12-30 19:38 UTC, MrArnoldPalmer commented on src/package-tag-group/index.ts
> +  }
Corresponding to the last comment, this method is essentially `bind`.
```ts
export interface PackageTagGroupProps {
  // ...
  // User's generally shouldn't need to extract values from classes when not necessary.
  readonly filterType?: FilterType;
}

export interface PackageTagGroupConfig {
  readonly id: string;
  readonly label?: string;
  readonly tooltip?: string;
  readonly filterType?: string;
}

export class PackageTagGroup {
  public readonly label?: string;
  public readonly tooltip?: string;
  public readonly filterType?: FilterType;

  constructor(public readonly id: string, props?: PackageTagGroupProps) {
    this.label = props?.label;
    this.tooltip = props?.tooltip;
    this.filterType = (props?.filterType ?? FilterType.checkbox()).value;
  }

  public bind(): PackageTagGroupConfig {
    return {
      id: this.id,
      label: this.label,
      tooltip: this.tooltip,
      filterType: this.filterType.bind(),
    };
  }
}
```
  
I can't find a super concise explanation of the `bind` pattern but for `TagCondition` I was referencing [`@aws-cdk/aws-lambda.Code`](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda/lib/code.ts#L145).

2021-12-30 20:45 UTC, gabewomble commented on src/package-tag-group/index.ts
> +}
Cool! I don't do enough OOP to have considered this, will update 👍

2022-01-03 19:11 UTC, merged