feat: tag packages with multiple construct frameworks
cdklabs/construct-hub pull request #794
Opened 2022-03-12 00:01 UTC by Chriscbr

Fixes #717

The changes required to support this in the front-end have already been added in https://github.com/cdklabs/construct-hub-webapp/pull/912.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-03-12 00:03 UTC, Chriscbr commented
Aside from the unit tests, I tested this by re-ingesting one package so far (and validated the multi-cdk tag now appeared on the front end) -- I'm now running a full reprocessing of the entire catalog to double check that there are no other issues.

2022-03-14 09:24 UTC, RomainMuller requested changes

2022-03-14 09:24 UTC, RomainMuller commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +  const detectedFrameworks: { [P in ConstructFrameworkName]?: number | 'not-sure' | 'ambiguous' } = {};
Not a fan of `'not-sure'`... It feels semantically too close to `'ambiguous'`, and you have to read the comments to understand what each means.

Alternate suggestions (without having thought all that much about it):
- `undefined` (e.g: no data)
- `'inconclusive'` (e.g: not enough data)
- `'no-data'`
- `'insufficient-data'`

That being said - from my earlier comment... MAYBE we should actually report ALL major versions we see of ALL frameworks we see... There's a valid use-case to have for construct libraries that are in fact designed to work with SEVERAL DISTINCT major versions of a framework (there's that package that is basically a bag of constants for IAM action names, etc... this can be used with any AWS CDK version)

2022-03-14 09:24 UTC, RomainMuller commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +  const frameworks: ConstructFramework[] = [];
```suggestion
  const frameworks = new Array<ConstructFramework>();
```

2022-03-14 09:24 UTC, RomainMuller commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +        const frameworkVersion: number | 'not-sure' | 'ambiguous' | undefined = detectedFrameworks[frameworkName];
Is the type annotation _really_ necessary here?

```suggestion
        const frameworkVersion = detectedFrameworks[frameworkName];
```

2022-03-14 09:24 UTC, RomainMuller commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +        const packageMajor: number | 'not-sure' = (versionRange ? minVersion(versionRange)?.major : undefined) ?? 'not-sure';
Same here - feels like the type annotation should be inferred by the compiler (as much as I prefer having type annotations on public/exported members, I prefer NOT to have them on local variables unless they cannot be correctly inferred by the compiler).

```suggestion
        const packageMajor = (versionRange ? minVersion(versionRange)?.major : undefined) ?? 'not-sure';
```

2022-03-14 09:24 UTC, RomainMuller commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +          return;
This looks like we should have had an early exit before going to try and work out the value for `packageMajor` (not a big deal, though, I kind of like how all the branching logic is in the same place here... it can be a little confusing though that when you look at the conditions here you can get confused as to whether we're checking the "currently registered" versus "newly found" value).

2022-03-14 09:24 UTC, RomainMuller commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +        }
I'd argue there's a missing `else` clause here... Supposedly, when you reach that final `else if`, `frameworkVersion` is guaranteed to be a number...

So Maybe switch to:

```suggestion
        } else {
          // At this point, frameworkVersion can only be a MV number
          assert(typeof frameworkVersion === 'number');
          
          // We've seen evidence of a particular major version for this
          // framework, so only update if this package conflicts with what
          // we're expecting.
          if (packageMajor !== 'not-sure' && frameworkVersion !== packageMajor) {
            detectedFrameworks[frameworkName] = 'ambiguous';
          }
          return;
        }
```

2022-03-14 09:24 UTC, RomainMuller commented on src/backend/ingestion/ingestion.lambda.ts
> +        constructFrameworks,
Has the UI _already_ been updated to render based on `constructFrameworks` if present, and fall back to `constructFramework` otherwise? If not, that should happen first, or this needs to at least temporarily continue setting `constructFramework` to "the one" value in `constructFrameworks` when its length is `=== 1`.

2022-03-14 22:19 UTC, Chriscbr commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +        const packageMajor: number | 'not-sure' = (versionRange ? minVersion(versionRange)?.major : undefined) ?? 'not-sure';
Good call. Yeah I was thinking of adding this superfluously just to make the code more readable / more clear that I'm doing a case analysis based on the type later in the code -- but I forgot this can have the side effect of accidentally broadening the type unintentionally, so I'm okay with dropping this.

2022-03-14 22:23 UTC, Chriscbr commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +          return;
Ah, I see your point, yeah this branch has nothing to do with `packageMajor`. I'll shift it over

2022-03-14 22:29 UTC, Chriscbr commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +  const detectedFrameworks: { [P in ConstructFrameworkName]?: number | 'not-sure' | 'ambiguous' } = {};
Agreed on the naming ambiguity -- 'no-data' sounds more clear here.

2022-03-14 22:31 UTC, Chriscbr commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +  [ConstructFrameworkName.CDK8S]: (name: string) => name === 'cdk8s' || /^cdk8s-plus(?:-(?:17|20|21|22))?$/.test(name),
Yep. 👍  I could preemptively add other numbers, but it's probably not "correct" to do so until we actually publish them. (Also to be honest I'm not sure this check is really needed, since just relying on cdk8s should be good enough, but 🤷 )

2022-03-14 22:32 UTC, Chriscbr commented on src/backend/ingestion/ingestion.lambda.ts
> +        constructFrameworks,
Yup! It's all ready for this change / will automatically look both formats, preferring the newer one if it exists.

2022-03-14 22:41 UTC, Chriscbr commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +import assert = require('assert');
For node/ESM related reasons I couldn't import this with either `import { assert } from 'assert'` or `import assert from 'assert'` without updating our `esModuleInterop` flag or something like that -- so I just had to import it like this. I don't think this is worth sweating over :P

2022-03-14 22:53 UTC, Chriscbr commented
> Should it instead classify as BOTH?

This sounds interesting! - though I think providing extra information is a bit beyond the scope of this PR and the planned changes discussed in the original issue. 😅 For now, if a package happens to support multiple major versions, we'll still show the framework(s), just without the "v1" text, so our bases should be covered.

I don't think this needs to be flagged as a breaking change because the front-end code we are bundling this package with includes backwards-compatible logic for parsing either format produced by the backend. Though, it does raise the question of if we ever did make a backwards-incompatible change to the _front-end_, we don't currently have a mechanism to enforce a major version bump when that change is imported here (via the `devDependencies`), so... that's something to think about for the future.

2022-03-15 09:10 UTC, RomainMuller commented on src/backend/ingestion/framework-detection.lambda-shared.ts
> +import assert = require('assert');
I've usually been able to use `import * as assert from 'assert';` without touching `esModuleInterop`.

2022-03-15 09:13 UTC, RomainMuller approved these changes

2022-03-15 09:13 UTC, merged