feat: add on call metric dashboard
cdklabs/construct-hub pull request #829
Opened 2022-04-01 17:14 UTC by yuth

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-04-04 18:54 UTC, Chriscbr requested changes
This looks like a great start! I've added several comments about the API but the overall structure of the classes makes sense.   👍

Could you update the PR description when you have a chance? It would be awesome to include a screenshot of the dashboard for others to see!

2022-04-04 18:54 UTC, Chriscbr commented on src/on-call-dashboard/index.ts
> +  });
Since these values are constants, I don't think they should be instance variables/members. How about we define these as const values outside of the class, or as private static members?

2022-04-04 18:54 UTC, Chriscbr commented on src/on-call-dashboard/sqs-dlq-widget.ts
> +export class SQSDLQWidget extends ConcreteWidget {
Add docstrings

2022-04-04 18:54 UTC, Chriscbr commented on src/on-call-dashboard/sqs-dlq-widget.ts
> +    this.nonEmptyQueueMessage = props.nonEmptyQueueMessage ?? 'There are some message in the DLQ. The table below lists the queues with non-empty DLQs. Please check the DLQs and re-drive the messages
I think these messages could be confusing since it says "the DLQ" even though there might be multiple? Can we update the default text to make this more clear? Or perhaps display the emptyQueueMessage for each DLQ?

2022-04-04 18:54 UTC, Chriscbr commented on src/on-call-dashboard/index.ts
> +    expression: 'SERVICE_QUOTA(mLambdaUsage)',
TIL about this cloudwatch capability!

2022-04-04 18:54 UTC, Chriscbr commented on src/on-call-dashboard/index.ts
> +  private addLambdaServiceQuotaWidgetToOnCallDashboard() {
<img width="683" alt="Screen Shot 2022-04-04 at 11 30 53 AM" src="https://user-images.githubusercontent.com/5008987/161608779-70b5fb66-ab14-40cb-a5e5-e12b35a3e457.png">

This is what my graph looks like on my Construct Hub (it looks like around a dozen metrics are shown) - I'm wondering how I should I be interpreting this? Also, maybe we can add a text widget to the right that explains how to read the different graphs?

2022-04-04 18:54 UTC, Chriscbr commented on src/on-call-dashboard/index.ts
> +    this.onCallDashboard = new Dashboard(this, 'On-Call dashboard', { dashboardName: 'OnCall' });
Actually it looks like we also have a field named `backendDashboardName`: https://github.com/cdklabs/construct-hub/blob/main/docs/application-overview.md#monitoring--alarming

Maybe we can reuse this and pass it as an option to this construct

2022-04-04 18:54 UTC, Chriscbr commented on src/on-call-dashboard/sqs-dlq-stats-widget-function.lambda.ts
> +function generateTable(data: Record<string, number>, queueConfigs: Record<string, QueueConfig>, widgetContext: WidgetContext): string {
Do you have any screenshots of what the SQS widget looks like when there are errors? My DLQ was empty when I was testing so I wasn't able to check this part 😅

2022-04-11 20:39 UTC, yuth commented on src/on-call-dashboard/sqs-dlq-stats-widget-function.lambda.ts
> +function generateTable(data: Record<string, number>, queueConfigs: Record<string, QueueConfig>, widgetContext: WidgetContext): string {
![image](https://user-images.githubusercontent.com/511386/162827922-a46d59d1-1f22-424a-bc2b-7000ac7c10c6.png)

2022-04-11 21:00 UTC, yuth commented on src/on-call-dashboard/index.ts
> +  private addLambdaServiceQuotaWidgetToOnCallDashboard() {
One thing I wanted to show in this widget was to give indication of which lambda function is making a huge dent in the quota, but with so many lambdas it makes the graph look cluterred. Do you have any suggestions for this graph?

2022-04-11 21:59 UTC, Chriscbr commented on src/on-call-dashboard/index.ts
> +  private addLambdaServiceQuotaWidgetToOnCallDashboard() {
Maybe we could just show the quota usage percentages? This way even if the metrics are all on different scales, as long as the values are well less than 1.0 (or less than 100 if we multiply all the values by 100) then we are not close to the quota. Another idea could be to instead just show a pair of number displays, one showing the `max_over_past_week(metric)`, and the second showing `service_quota(metric)`, and this way the user doesn't need to see the trends. (Or maybe the trends are nice to see, no strong preference from me. 🙂)

2022-04-11 22:01 UTC, Chriscbr commented on src/on-call-dashboard/index.ts
> +  private addLambdaServiceQuotaWidgetToOnCallDashboard() {
Also I was wondering if we should measure our usage against any other quotas. I think fargate usage (number of active tasks) might be one to consider since our service has come up against that limit a few times in the past.

2022-04-12 17:39 UTC, Chriscbr approved these changes
Great work Yathi! I had a few more nits but none of them are blocking, so I left the `pr/do-not-merge` label so you can make any changes and merge in when ready. 👍

2022-04-12 17:39 UTC, Chriscbr commented on src/backend/orchestration/index.ts
> +  readonly onCallDashboard: OverviewDashboard;
It looks like we're referring to this as both the oncall dashboard and overview dashboard -- we should probably just use one term everywhere and be consistent since this is technically part of the public API. This appears in a few couple other places as well
```suggestion
  readonly overviewDashboard: OverviewDashboard;
```

2022-04-12 17:39 UTC, Chriscbr commented on src/backend/inventory/index.ts
> +  readonly onCallDashboard: OverviewDashboard;
```suggestion
  readonly overviewDashboard: OverviewDashboard;
```

2022-04-12 17:39 UTC, Chriscbr commented on src/overview-dashboard/index.ts
> +export interface OverviewDashboardProps {
```suggestion
/**
 * Properties for OverviewDashboard
 */
export interface OverviewDashboardProps {
```

2022-04-12 17:39 UTC, Chriscbr commented on src/overview-dashboard/index.ts
> +  public addDistributionMetricToDashboard(distribution: IDistribution) {
```suggestion
  public addDistributionMetricToDashboard(distribution: IDistribution) {
```

2022-04-12 17:39 UTC, Chriscbr commented on src/overview-dashboard/sqs-dlq-stats-widget-function.lambda.ts
> +  console.log(event);
I think this can help prevent the object from getting truncated if the `event` is very big for some reason. Just a good practice
```suggestion
  console.log(JSON.stringify(event));
```

2022-04-12 17:39 UTC, Chriscbr commented on src/overview-dashboard/sqs-dlq-stats-widget-function.lambda.ts
> +        .filter(([_, count]) => count > 0)
Can the number of messages be negative...? 😮  Maybe consider adding a comment

2022-04-12 17:39 UTC, Chriscbr commented on src/overview-dashboard/sqs-dlq-stats-widget-function.lambda.ts
> +This is useful for embedding the same text context in multiple dashboards and update it from a central place. An example would be a menu of links between dashboards.
I'm guessing this was copied from sample code - we can probably remove it 
```suggestion
```

2022-04-12 19:08 UTC, yuth commented on src/overview-dashboard/sqs-dlq-stats-widget-function.lambda.ts
> +        .filter(([_, count]) => count > 0)
No, but messages can be `0`. Dont want to show DLQ where there are no messages

2022-04-12 19:47 UTC, Chriscbr approved these changes

2022-04-12 20:05 UTC, merged