feat: add support for feed
cdklabs/construct-hub pull request #855
Opened 2022-04-21 00:45 UTC by yuth

Add support for generating RSS/ATOM feed when new packages get ingested. The feed will include the release notes for the release if the notes are available in GitHub.

To fetch the feed, the construct needs to be configured with GitHub token, so the release notes fetching from GitHub does not get throttled due to API rate limits. If the GitHub tokens are not passed, the construct does not generate release notes and no feeds will be generated
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-04-22 23:09 UTC, Chriscbr requested changes
Really great work @yuth. Can't wait to ship this :)

2022-04-22 23:09 UTC, Chriscbr commented on src/backend/release-notes/index.ts
> +    props.monitoring.addHighSeverityAlarm(
I wonder if these should be high severity alarms. We definitely want to get ticketed about unexpected problems, but if parts of the RSS feed processing isn't working, I don't know if it's critical enough to be pager-worthy. We can always tweak this later if needed though

2022-04-25 21:20 UTC, yuth commented on src/backend/release-notes/index.ts
> +    }
To break cyclic dependency. We dont have the webapp created when the `feed-builder` is internalized

2022-04-25 21:21 UTC, yuth commented on src/__tests__/devapp/snapshot.test.ts
> +  process.env.GITHUB_TOKEN = 'arn:aws:secretsmanager:us-east-2:111111111:secret:some-secret-1aa11a';
Yes, we need to add some details about getting release notes. The test code need not change as this is brute forcing the evn var for the test.

2022-04-25 21:36 UTC, yuth commented on src/backend/ingestion/ingestion.lambda.ts
> +      }
I added a new field in the reingestion SQS message to prevent re-generation release notes

2022-04-25 22:03 UTC, yuth commented on src/backend/release-notes/release-notes-trigger.lambda.ts
> +    if (await isStepFunctionAlreadyRunning()) return;
We want only one instance of step function running at any time. After the execution of step function, it will re-run itself to process any message left in the queue. So the lambda function is has to execute the step function only when there is no active execution of step function is going on

2022-04-25 22:13 UTC, yuth commented on src/backend/release-notes/release-notes-trigger.lambda.ts
> +  if (await isStepFunctionAlreadyRunning()) {
I am not sure of a way to do it

2022-04-25 22:18 UTC, yuth commented on src/backend/release-notes/release-notes-trigger.lambda.ts
> +    if (index > 0 && index % 10 === 0) {
Batch message send has the limit of sending 10 message at once. So we are batching the messages

2022-04-25 22:32 UTC, yuth commented on src/backend/release-notes/generate-release-notes.lambda.ts
> +function getGithubRepoDetails(
There is already unit tests for these
https://github.com/cdklabs/construct-hub/blob/1449bd36e2f9194d3b8ac1661fb033801f243a38/src/__tests__/backend/release-notes/generate-release-notes.lambda.test.ts#L142
https://github.com/cdklabs/construct-hub/blob/1449bd36e2f9194d3b8ac1661fb033801f243a38/src/__tests__/backend/release-notes/generate-release-notes.lambda.test.ts#L177

2022-04-25 22:43 UTC, yuth commented on src/backend/release-notes/index.ts
> +    this.queue = new sqs.Queue(this, 'ChangeLogFetchQueue', {
To support rate limited API request we need 2 queues. The fetchQueue is an external queue where others send messages to. This queue triggers a lambda and copies to messages to worker queue and the starts step function execution if there isnt one running.

The worker queue is consumed by step function and when the messages are processed it will look for more in the worker queue by restarting itself. When all the messages are consumed, the step function will not execute itself.

This is where the fetch queue comes to play. When a new messages comes in the lambda will copy it to worker queue and start the execution of the step function

2022-04-25 23:01 UTC, yuth commented on src/construct-hub.ts
> +      releaseNotes = new ReleaseNoteFetcher(this, 'ReleaseNotes', {
Refactored feed generation to a separate construct, feed should be generated even when no release notes are fetched from GH

2022-04-25 23:04 UTC, yuth commented on src/backend/ingestion/ingestion.lambda.ts
> +          tarballUri: `s3://${BUCKET_NAME}/${packageKey}`,
This is the same approach the ingestion function takes. So not sure if we should have different apprach

2022-04-25 23:04 UTC, yuth commented on src/backend/release-notes/index.ts
> +import { ComparisonOperator, Metric, MetricOptions, Statistic, TreatMissingData } from '@aws-cdk/aws-cloudwatch';
Done

2022-04-26 00:16 UTC, Chriscbr commented on src/backend/release-notes/index.ts
> +    this.queue = new sqs.Queue(this, 'ChangeLogFetchQueue', {
I think I'm still a little confused... What would happen if we just used one queue for that process? I'm imagining if a message appears in the fetch queue, then that triggers a lambda which starts the step function if none are running. That step function consumes messages from the fetch queue as long as there are messages left, otherwise it goes to sleep. Whenever new messages are inserted, the lambda will do nothing if the step function isn't running, and it will start the step function back up otherwise.

How does rate limiting play into this?

2022-04-26 00:33 UTC, Chriscbr commented on src/backend/ingestion/ingestion.lambda.ts
> +          tarballUri: `s3://${BUCKET_NAME}/${packageKey}`,
Ah I see, got it

2022-04-26 23:41 UTC, Chriscbr commented on src/backend/catalog-builder/index.ts
> +    }));
```suggestion
    handler.grantInvoke(props.feedBuilder.updateFeedFunction);
```

2022-04-27 15:55 UTC, Chriscbr approved these changes

2022-04-27 15:55 UTC, merged

2022-04-27 16:04 UTC, moltar commented
Thanks @yuth! 🎉