feat: add (very) basic back-end monitoring
cdklabs/construct-hub pull request #91
Opened 2021-06-17 12:48 UTC by RomainMuller

Introduce very basic monitoring for back-end Lambda functions.
Currently this does not trigger any actions, but ensures an
operational dashboard is available with a bird's eye view on
the back-end.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-06-17 14:34 UTC, eladb requested changes

2021-06-17 14:34 UTC, eladb commented on src/backend/discovery/index.ts
> +    props.monitoring.addHighSeverityAlarm(
High severity means SEV2. I think this is not user-facing

2021-06-17 15:19 UTC, RomainMuller commented on src/backend/discovery/index.ts
> +    props.monitoring.addHighSeverityAlarm(
Arguably it is - you have been pushing for us to have a 10 minutes "published in npm --> available on construct hub" SLA, which would make a hiccup there a possible way to violate this SLA.

I don't feel very strongly that this should be a SEV-2 however... the SLA may be a "soft" SLA (aspirational, not contractual)... WDYT?

2021-06-22 15:24 UTC, iliapolo approved these changes

2021-06-22 15:25 UTC, eladb commented on src/backend/discovery/index.ts
> +    props.monitoring.addHighSeverityAlarm(
Still don't feel like a SEV-2 and also doesn't feel like the right monitor for this SLA. If we want to manage this SLA we need a dedicated monitor, and even then, I wouldn't say it's SEV-2.

2021-06-22 15:38 UTC, merged

2021-06-22 16:56 UTC, eladb reviewed
@RomainMuller where is the part that we actually associate these alarms to actions?