feat: monitor ECS tasks and kill runway ones
cdklabs/construct-hub pull request #961
Opened 2022-08-10 14:39 UTC by RomainMuller

A small amount of ECS tasks appear to never terminate despite
all of our efforts to time them out properly. ECS currently
does not support setting task timeouts that are service-enforced
so deploying a small monitor to do this job for us.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-15 09:02 UTC, iliapolo requested changes

2022-08-15 09:02 UTC, iliapolo commented on src/backend/ecs-task-monitor/monitor.lambda.ts
> +            .stopTask({
Will SFN send the message to the DLQ in this case as well? I suppose:

https://github.com/cdklabs/construct-hub/blob/b101f005816937978d39db53a75b2a50b30075d4/src/backend/orchestration/index.ts#L421-L424

Takes care of it?

2022-08-15 09:02 UTC, iliapolo commented on src/backend/ecs-task-monitor/index.ts
> +  public metricTaskAge(
Let's also add these metrics to a dashboard already as well?

2022-08-18 08:46 UTC, RomainMuller commented on src/backend/ecs-task-monitor/index.ts
> +   * The age of all active tasks on the monitored ECS cluster.
It's only the maximum if you leave the default statistic enabled... so I don't want the description to imply it's only/always the maximum.

2022-08-18 08:52 UTC, RomainMuller commented on src/backend/ecs-task-monitor/monitor.lambda.ts
> +            .stopTask({
Yes. This is already happening today... Except the ECS tasks stay there sitting idle forever for some unexplainable reason.

2023-06-07 09:28 UTC, merged