chore: un-pin devDependencies, to solve mysterious yarn error
cdklabs/construct-hub pull request #97
Opened 2021-06-18 13:24 UTC by RomainMuller

When the dependencies are pinned to a particular version, which is NOT
the latest available version, we consistently get a mysterious yarn
error ('expected hoisted manifest') around the cdk-watchful peerDependency
on @aws-cdk/* packages.

Awkwardly, un-pinning makes the error go away... So here I am... un-pinning.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-06-18 16:34 UTC, MrArnoldPalmer approved these changes

2021-06-18 17:38 UTC, NetaNir requested changes
We have to pin the `devDependencies`. See this PR: https://github.com/cdklabs/construct-hub/pull/95 which explains it.

2021-06-18 17:41 UTC, NetaNir commented on package.json
> +    "@aws-cdk/cx-api": "^1.108.0",
why downgrading the version?

2021-06-21 08:02 UTC, RomainMuller commented
> We have to pin the `devDependencies`. See this PR: #95 which explains it.

In that situation, I found myself unable to run `yarn install` as this would result in `expected hoisted manifest` as soon as any transitive dependency has a caret dependency that resolves to a version that is  `!=` from the one we pin to (which becomes the case on every new release of one of those)...

2021-06-21 15:36 UTC, closed without merging